apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  namespace: open5gs
data:
  nrf.yaml: |
    logger:
      file: /var/log/open5gs/nrf.log
      level: info
    
    nrf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  namespace: open5gs
data:
  amf.yaml: |
    logger:
      file: /var/log/open5gs/amf.log
      level: info
    
    amf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
      ngap:
        - addr: 0.0.0.0
      metrics:
        - addr: 0.0.0.0
          port: 9090
      guami:
        - plmn_id:
            mcc: 001
            mnc: 01
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 001
            mnc: 01
          tac: 1
      plmn_support:
        - plmn_id:
            mcc: 001
            mnc: 01
          s_nssai:
            - sst: 1
      security:
        integrity_order:
          - NIA2
          - NIA1
          - NIA0
        ciphering_order:
          - NEA0
          - NEA1
          - NEA2
      network_name:
        full: Open5GS
      amf_name: open5gs-amf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs
data:
  smf.yaml: |
    logger:
      file: /var/log/open5gs/smf.log
      level: info
    
    smf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
      pfcp:
        - addr: 0.0.0.0
      gtpc:
        - addr: 0.0.0.0
      gtpu:
        - addr: 0.0.0.0
      metrics:
        - addr: 0.0.0.0
          port: 9090
      subnet:
        - addr: 10.45.0.1/16
          dnn: internet
      dns:
        - 8.8.8.8
        - 8.8.4.4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  namespace: open5gs
data:
  upf.yaml: |
    logger:
      file: /var/log/open5gs/upf.log
      level: info
    
    upf:
      pfcp:
        - addr: 0.0.0.0
      gtpu:
        - addr: 0.0.0.0
      subnet:
        - addr: 10.45.0.1/16
          dnn: internet
      metrics:
        - addr: 0.0.0.0
          port: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  namespace: open5gs
data:
  ausf.yaml: |
    logger:
      file: /var/log/open5gs/ausf.log
      level: info
    
    ausf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  namespace: open5gs
data:
  udm.yaml: |
    logger:
      file: /var/log/open5gs/udm.log
      level: info
    
    udm:
      sbi:
        - addr: 0.0.0.0
          port: 7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  namespace: open5gs
data:
  udr.yaml: |
    logger:
      file: /var/log/open5gs/udr.log
      level: info
    
    udr:
      sbi:
        - addr: 0.0.0.0
          port: 7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  namespace: open5gs
data:
  pcf.yaml: |
    logger:
      file: /var/log/open5gs/pcf.log
      level: info
    
    pcf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
      metrics:
        - addr: 0.0.0.0
          port: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: open5gs
data:
  nssf.yaml: |
    logger:
      file: /var/log/open5gs/nssf.log
      level: info
    
    nssf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
      nsi:
        - addr: 0.0.0.0
          port: 7777
          s_nssai:
            sst: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-bsf-config
  namespace: open5gs
data:
  bsf.yaml: |
    logger:
      file: /var/log/open5gs/bsf.log
      level: info
    
    bsf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-webui-config
  namespace: open5gs
data:
  webui.yaml: |
    logger:
      file: /var/log/open5gs/webui.log
      level: info
    
    webui:
      server:
        - addr: 0.0.0.0
          port: 3000
